version: '3.8'

services:

  server:
    container_name: cogent.server
    build: ./server
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./server/app:/app
    ports:
      - 8000:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0

  worker:
    container_name: cogent.celery
    build: ./server
    volumes:
      - ./server/app:/app
    entrypoint: celery --app=workers.celery_main.celery_app worker -c 2 --loglevel=debug
    depends_on:
      - rabbit
      - redis

  rabbit:
    container_name: cogent.rabbit
    image: rabbitmq:latest

  redis:
    container_name: cogent.redis
    image: redis:latest
